# Copyright 2026 bburda
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# SwaggerUI.cmake - Download and embed Swagger UI assets at configure time
#
# When ENABLE_SWAGGER_UI=ON, downloads swagger-ui-dist files from unpkg.com
# and generates a C++ source file with embedded byte arrays.
# The generated file is added to the gateway_ros2 target (the ROS adapter
# layer that owns the HTTP server and Swagger UI integration).

set(SWAGGER_UI_VERSION "5.17.14")
set(SWAGGER_UI_URL "https://unpkg.com/swagger-ui-dist@${SWAGGER_UI_VERSION}")

set(SWAGGER_UI_DIR "${CMAKE_CURRENT_BINARY_DIR}/swagger-ui")
set(SWAGGER_UI_GENERATED_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated")
set(SWAGGER_UI_ASSETS_CPP "${SWAGGER_UI_GENERATED_DIR}/swagger_ui_assets_data.cpp")

file(MAKE_DIRECTORY ${SWAGGER_UI_DIR})
file(MAKE_DIRECTORY ${SWAGGER_UI_GENERATED_DIR})

message(STATUS "Swagger UI: enabled (version ${SWAGGER_UI_VERSION})")

set(_swagger_files
  swagger-ui-bundle.js
  swagger-ui.css
  swagger-ui-standalone-preset.js
)

set(_download_ok TRUE)

foreach(_file ${_swagger_files})
  set(_dest "${SWAGGER_UI_DIR}/${_file}")
  if(NOT EXISTS "${_dest}")
    message(STATUS "  Downloading ${_file}...")
    # SHA256 hashes for integrity verification
    set(_hash_swagger_ui_bundle_js "c2e4a9ef08144839ff47c14202063ecfe4e59e70a4e7154a26bd50d880c88ba1")
    set(_hash_swagger_ui_css "40170f0ee859d17f92131ba707329a88a070e4f66874d11365e9a77d232f6117")
    set(_hash_swagger_ui_standalone_preset_js "33b7a6f5afcac4902fdf93281be2d2e12db15f241d384606e6e6d17745b7f86f")

    # Convert filename to variable-safe key (replace - and . with _)
    string(REPLACE "-" "_" _hash_key "${_file}")
    string(REPLACE "." "_" _hash_key "${_hash_key}")

    file(DOWNLOAD
      "${SWAGGER_UI_URL}/${_file}"
      "${_dest}"
      STATUS _status
      TIMEOUT 60
      EXPECTED_HASH SHA256=${_hash_${_hash_key}}
    )
    list(GET _status 0 _code)
    if(NOT _code EQUAL 0)
      list(GET _status 1 _msg)
      message(WARNING "  Failed to download ${_file}: ${_msg}")
      set(_download_ok FALSE)
      # Clean up partial download
      file(REMOVE "${_dest}")
    endif()
  endif()
endforeach()

if(_download_ok)
  message(STATUS "  Generating embedded assets source file...")

  # C++ variable name mapping (replace hyphens/dots with underscores)
  set(_var_names "")
  list(APPEND _var_names "swagger_ui_bundle_js")
  list(APPEND _var_names "swagger_ui_css")
  list(APPEND _var_names "swagger_ui_standalone_preset_js")

  # Generate .cpp file with embedded byte arrays using xxd
  file(WRITE "${SWAGGER_UI_ASSETS_CPP}"
"// Auto-generated by SwaggerUI.cmake - do not edit
#include \"swagger_ui_assets.hpp\"

namespace ros2_medkit_gateway {
namespace swagger_ui {

")

  list(LENGTH _swagger_files _num_files)
  math(EXPR _last_idx "${_num_files} - 1")

  foreach(_idx RANGE ${_last_idx})
    list(GET _swagger_files ${_idx} _file)
    list(GET _var_names ${_idx} _var)

    # Use xxd to generate C array
    execute_process(
      COMMAND xxd -i "${_file}"
      WORKING_DIRECTORY "${SWAGGER_UI_DIR}"
      OUTPUT_VARIABLE _xxd_output
      RESULT_VARIABLE _xxd_result
    )

    if(NOT _xxd_result EQUAL 0)
      message(FATAL_ERROR "xxd failed for ${_file}")
    endif()

    # xxd generates: unsigned char filename[] = { ... }; unsigned int filename_len = NNN;
    # Replace the xxd-generated variable names with our namespaced ones.
    string(REPLACE "-" "_" _xxd_var "${_file}")
    string(REPLACE "." "_" _xxd_var "${_xxd_var}")

    string(REPLACE
      "unsigned char ${_xxd_var}"
      "const unsigned char ${_var}"
      _xxd_output "${_xxd_output}"
    )
    string(REPLACE
      "unsigned int ${_xxd_var}_len"
      "const size_t ${_var}_size"
      _xxd_output "${_xxd_output}"
    )

    file(APPEND "${SWAGGER_UI_ASSETS_CPP}" "${_xxd_output}\n")
  endforeach()

  file(APPEND "${SWAGGER_UI_ASSETS_CPP}"
"
}  // namespace swagger_ui
}  // namespace ros2_medkit_gateway
")
  message(STATUS "  Generated ${SWAGGER_UI_ASSETS_CPP}")

else()
  message(FATAL_ERROR "Swagger UI: failed to download required assets. "
    "Build with -DENABLE_SWAGGER_UI=OFF to skip Swagger UI, "
    "or ensure network access to unpkg.com during CMake configure.")
endif()

# Add generated source to gateway_ros2 and make the header findable
target_sources(gateway_ros2 PRIVATE "${SWAGGER_UI_ASSETS_CPP}")
target_include_directories(gateway_ros2 PRIVATE
  "${CMAKE_CURRENT_SOURCE_DIR}/src/http"
)
