# Copyright 2026 mfaferek93
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# VDA 5050 v2.0.0 - MaxArrayLens (Factsheet sub-type)
# Maximum array lengths supported by this AGV. All optional.

uint32 order_nodes
uint32 order_edges
uint32 node_actions
uint32 edge_actions
uint32 actions_action_parameters
uint32 instant_actions
uint32 trajectory_knot_vector
uint32 trajectory_control_points
uint32 state_node_states
uint32 state_edge_states
uint32 state_loads
uint32 state_action_states
uint32 state_errors
uint32 state_information
uint32 error_error_references
uint32 information_info_references
